### ISSUE TITLE
Bug: Change username 

### ISSUE THREAD

**Issue by dberkerdem** [SWE-574-GROUP-1/SWE574-GROUP-1#12]
Changing username should also change the username in liked_by attribute in all posts

**Comment by dberkerdem** [comment]
Changing username feature is temporarily disabled.

**Comment by Fluentum** [comment]
Information will be saved based on ID. Currently it is user name.

**Comment by kaancanblogo** [comment]
https://github.com/SWE-574-GROUP-1/SWE574-GROUP-1/pull/76
