### ISSUE TITLE
Bug: Follow feature in search page

### ISSUE THREAD

**Issue by dberkerdem** [SWE-574-GROUP-1/SWE574-GROUP-1#13]
Follow feature in search page redirect the user to an empty page and should be fixed.

**Comment by dberkerdem** [comment]
Follow feature in search page is temporarily disabled

**Comment by Fluentum** [comment]
To be re-activated later on.

**Comment by akyagmur** [comment]
https://github.com/SWE-574-GROUP-1/SWE574-GROUP-1/commit/7ebd75408c8a499f7b723c7fed9b8d059ca74046
