### ISSUE TITLE
Refactor: HTML navbar inheritance

### ISSUE THREAD

**Issue by dberkerdem** [SWE-574-GROUP-1/SWE574-GROUP-1#30]
Navbar should be inherited from navbar.html and must be refactored within the following files
- [x] base.html
- [x] feed.html
- [x] profile.html
- [x] search.html
- [x] settings.html
- [x] signin.html
- [x] signup.html
- [x] spaces.html
- [x] tags.html

**Comment by Fluentum** [comment]
feed.html	->inherits from base inside
profile.html ->inherits from base inside
search.html ->inherits from base inside
settings.html -> inherits from navbar.html
signin.html -> should have own nav-bar
signup.html -> should have own nav-bar
spaces.html -> should have own nav-bar
tags.html -> inherits from base inside
