### ISSUE TITLE
Feature: Addition of like button for the post

### ISSUE THREAD

**Issue by Fluentum** [SWE-574-GROUP-1/SWE574-GROUP-1#45]
R - The post shall include like button. Users shall like or dislike a post. Readers, writers, moderators and space owner has this right. When clicked on the same button, like or dislike can be taken back.

- [x] Like
- [x] Dislike
- [x] User cancellation of like
- [x] User cancellation of dislike

**Comment by gencaypolat** [comment]
Like button is added and tested.
