### ISSUE TITLE
Enhancement : Space Name, Description, Avatar Features

### ISSUE THREAD

**Issue by damlaalkan** [SWE-574-GROUP-1/SWE574-GROUP-1#53]
Spaces shall be public for all users and include the features below:

- [ ] Unique Name
- [ ] Description
- [ ] Optional Avatar / Photo

**Comment by dberkerdem** [comment]
Implemented in [PR](https://github.com/SWE-574-GROUP-1/SWE574-GROUP-1/pull/115)
