### ISSUE TITLE
Bug: Delete account feature redirection

### ISSUE THREAD

**Issue by dberkerdem** [SWE-574-GROUP-1/SWE574-GROUP-1#95]
Delete account feature does not redirect to sign up feature. Eventhough it redirects you to the html, you cannot sign up to that page. You should refresh the page in order to sign up.

**Comment by dberkerdem** [comment]
To solve this, you may logout the user before deleting its profile

**Comment by Fluentum** [comment]
Models.py and views.py files revisited. Delete function redefined. Manual tests are done.

**Comment by Fluentum** [comment]
Issue can be closed again. Minor bug solved and merged.
